# this container defines the underlying OS for each job when using the workflow
workdir: "/cluster/projects/cesconlab/workspace/Guanqiao/workflow/WES_PDX_PDO_PatientTissue_Snakemake_v202509" # update as needed

##### load rules #####
include: "rules/common.smk"
include: "rules/align.smk"
include: "rules/gatk4.smk"
include: "rules/mutect2.smk"
include: "rules/mutect2_rescue.smk"
include: "rules/cnvkit.smk"

##### target rules #####

rule all:
    input:
        "results/maf/cohort_merged_final.maf",
        expand("results/cnvkit/{sample}/{sample}_scatter.pdf", sample=samples["sample_name"]),
        expand("results/cnvkit/{sample}/{sample}_diagram.pdf", sample=samples["sample_name"]),
	expand("results/cnvkit/{sample}/{sample}.gene_cnv.tsv", sample=samples["sample_name"]),
	expand("results/cnvkit/{sample}/{sample}.seg", sample=samples["sample_name"]),
	expand("results/picard/pe/{sample}_picard_align_matrix.txt", sample=samples["sample_name"])
