# this container defines the underlying OS for each job when using the workflow
workdir: "/cluster/projects/cesconlab/workspace/Guanqiao/workflow/RNAseq_test"

##### load rules #####
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/align.smk"
include: "rules/countmatrix.smk"

##### target rules #####

rule all:
    input:
        expand("results/xengsort/{sample}-graft.1.fq.gz", sample=samples["sample_name"]),
        expand("results/xengsort/{sample}-graft.2.fq.gz", sample=samples["sample_name"])